; MiniGO.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGO.java
.class public MiniGO
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 6
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 2
  .limit locals 1
  .line 8
  0: ldc "apple"
  2: ldc "banana"
  4: invokevirtual java/lang/String/compareTo(Ljava/lang/String;)I
  7: invokestatic io/putIntLn(I)V
  .line 9
  10: return
.end method

